services:
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ./:/app
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 3s
      retries: 3

  ui:
    build: .
    command: streamlit run ui/app.py --server.address 0.0.0.0 --server.port 8501
    ports:
      - "8501:8501"
    depends_on:
      - api
    environment:
      # The UI should call the API by service name inside the compose network
      - BACKEND_URL=http://api:8000
    volumes:
      - ./:/app